version: 2.1
orbs:
  node: circleci/node@3.0.0
  cypress: cypress-io/cypress@1
workflows:
  node-tests:
    jobs:
      - node/test
      - cypress/run:
          yarn: false
          start: npm start
          wait-on: 'http://localhost:3000'
          no-workspace: true
